services:
  mini-erp:
    restart: always
    build: .
    working_dir: /app
    container_name: mini-erp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mini-erp-db.chy4m8aky600.us-east-2.rds.amazonaws.com/mini_erp_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=v_*1vr)*hoOAK[UwCeC5T.A!]Tri
