CREATE TABLE tb_product (
	id bigint generated by default as identity,
	name varchar(100),
	price numeric(38,2),
	product_code varchar(20) unique,
	description varchar(255),
	unit varchar(255),
	primary key (id)
);