ALTER TABLE tb_product ALTER COLUMN name SET NOT NULL;
ALTER TABLE tb_product ALTER COLUMN price SET NOT NULL;
ALTER TABLE tb_product ALTER COLUMN product_code SET NOT NULL;
ALTER TABLE tb_product ALTER COLUMN description SET NOT NULL;
ALTER TABLE tb_product ALTER COLUMN unit SET NOT NULL;