create table tb_customers (
	type smallint not null check ((type between 0 and 1)),
	id bigint generated by default as identity,
	customer_name varchar(150) not null,
	email varchar(100) not null,
	cpf varchar(18) not null unique,
	telefone varchar(20) not null,
	observations varchar(255),
	primary key (id)
);