name: CI - Build, Test and Push to ECR

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Mostrar contexto do evento
        run: |
          echo "event_name=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "sha=${{ github.sha }}"

      - name: Configurar Java 21 + cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Configurar Docker
        uses: docker/setup-docker-action@v5.0.0

      - name: Build e testes com Maven
        run: mvn -B clean verify

      - name: ECR Login
        uses: thalesvon/ecr-login@1.0.0
